# Site settings
title: HansChen的主页
user_title: ~ Bug Writer ~
description: 个人主页
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "http://www.hanschen.site" # the base hostname & protocol for your site e.g. http://www.hanschen.site

# User settings
username: HansChen
user_description: ~ Bug Writer ~

blog: http://blog.hanschen.site
email: shensky711@gmail.com
github_username:  shensky711
gplus_username:  114746819615461693138

# Google-analytics
google-analytics:
  id: ""
  
# Baidu-analytics
baidu-analytics:
  id: "f6094a3315c4094c74835f2874f1b58d"

exclude: ['package.json', 'src' , 'node_modules']
